-- begin EVENTS_DEPARTMENT
alter table EVENTS_DEPARTMENT add constraint FK_EVENTS_DEPARTMENT_CHIEF12 foreign key (CHIEF_ID) references EVENTS_STUDENT(ID)^
create index IDX_EVENTS_DEPARTMENT_CHIEF12 on EVENTS_DEPARTMENT (CHIEF_ID)^
-- end EVENTS_DEPARTMENT

-- begin EVENTS_STUDENT
alter table EVENTS_STUDENT add constraint FK_EVENTS_STUDENT_DEPARTMENT foreign key (DEPARTMENT_ID) references EVENTS_DEPARTMENT(ID)^
alter table EVENTS_STUDENT add constraint FK_EVENTS_STUDENT_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_EVENTS_STUDENT_DEPARTMENT on EVENTS_STUDENT (DEPARTMENT_ID)^
create index IDX_EVENTS_STUDENT_USER on EVENTS_STUDENT (USER_ID)^
-- end EVENTS_STUDENT
-- begin EVENTS_EVENT
alter table EVENTS_EVENT add constraint FK_EVENTS_EVENT_CHIEF foreign key (CHIEF_ID) references EVENTS_STUDENT(ID)^
create index IDX_EVENTS_EVENT_CHIEF on EVENTS_EVENT (CHIEF_ID)^
-- end EVENTS_EVENT
